version: '3.8'
services:
  translate-modelscope:
    image: paidax/translate-modelscope:0.0.2
    container_name: fer-modelscope
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 9006:9006
    command: uvicorn main:app --port 9006 --host 0.0.0.0
