version: '3.8'
services:
  translate-modelscope:
    image: paidax/translate-modelscope:0.0.3
    container_name: translate-modelscope
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 9006:9006
    command: tail -f /dev/null
